language: ruby

# Only build tags
#if: tag IS present

env:
  matrix:
    - ARCH=x86_64
      DOCKERFILE=Dockerfile.amd64
    - ARCH=arm
      DOCKERFILE=Dockerfile.rpi

sudo: required

services:
  - docker

before_install:
  - VERSION=`cat VERSION`
  - LATESTVERSION=`curl https://raw.githubusercontent.com/CausticLab/hass-configurator-docker/master/VERSION`
  - DOCKER_BUILD=causticlab/hass-configurator-docker:${VERSION}-${ARCH}
  - DOCKER_BUILD_NOVER=causticlab/hass-configurator-docker:${ARCH}

install:
  - rm -rf ./src/
  - git clone https://github.com/danielperna84/hass-configurator.git ./src
  - sed -i 's/GIT = False/GIT = True/g' ./src/configurator.py

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t ${DOCKER_BUILD} -f ${DOCKERFILE} .
  - if [ $VERSION == $LATESTVERSION ];
    then docker tag ${DOCKER_BUILD} ${DOCKER_BUILD_NOVER};
    fi

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push ${DOCKER_BUILD}
  - if [ $VERSION == $LATESTVERSION ];
    then docker push ${DOCKER_BUILD_NOVER};
    fi

notifications:
  email: false
